### PR TITLE
Add a method to delete all customer's invoices (ch23545)

### PR DESCRIPTION
**Pull request by swember**
This PR adds `delete_all_invoices` method to `Customer` class

### CODE REVIEW

**Comment by pkopac** [comment]
@swember the test failure points to test randomness from missing sort, I think, can you fix it please?

**Comment by swember** [comment]
> @swember the test failure points to test randomness from missing sort, I think, can you fix it please?

It wasn't randomness, unfortunately. I am not sure what exactly it was.

**Comment by pkopac** [comment]
@swember you will need to bump up gem version and ask Ishan for release :)

**Comment by ikanade** [comment]
@pkopac  @swember  Maybe we should update documentation before releasing it.

**Comment by pkopac** [comment]
@ikanade actually the opposite - we first need to have the code out before we tell people to use it :) Imagine you open the reference docs and it has examples that don't work with the latest version of the library... that's weird.

**Pull request merged**
