### PR TITLE
Ruby client notes and call logs API support[sc-55268] 

### PR DESCRIPTION
**Pull request by SoeunSona**
API document: https://www.notion.so/chartmogul/API-endpoints-for-adding-notes-call-logs-798b788a08764549a334db5d48d65469?pvs=4

1. Create a note from customer
```
customer = ChartMogul::Customer.retrieve('cus_3819e09a-50a2-11ee-ada7-9fcf71cd4580')
customer.create_note(
  ....
)

ChartMogul::Note.create(data)
```

2. Get all notes from customer
```
customer = ChartMogul::Customer.retrieve('cus_3819e09a-50a2-11ee-ada7-9fcf71cd4580')
customer.notes

ChartMogul::Note.all(customer_uuid: customer_uuid)

```

3. Get a note

```
notes = ChartMogul::Note.retrieve('note_uuid')
```

4. Update a note
```
updated_note = ChartMogul::Note.update(data)
```

5. Delete a note
```
# `{}`
ChartMogul::Note.delete('note_uuid') 
```

### CODE REVIEW

**Comment by briwa** [comment]
Currently, there's an ongoing discussion (https://github.com/chartmogul/chartmogul-php/pull/116#issuecomment-1849239501) which would potentially change the way the interface is being implemented in PHP. The implementation for the Ruby client might also change depending on the outcome, so I will hold off on the review until then

**Review by briwa — COMMENTED** [review]
Currently, there's an ongoing discussion (https://github.com/chartmogul/chartmogul-php/pull/116#issuecomment-1849239501) which would potentially change the way the interface is being implemented in PHP. The implementation for the Ruby client might also change depending on the outcome, so I will hold off on the review until then

**Review by kmossco — APPROVED** [review]
LGTM. Should this already update the version of the library and the Changelog, though? Or should we do that in another PR? 🤔

**Comment by SoeunSona** [comment]
@kmossco Thank you for reviewing it! We will create another PR for updating the version of library and the Changelog!

**Review by briwa — APPROVED** [review]

**Pull request merged**
